### ISSUE TITLE
Create some tasks please

### ISSUE THREAD

**Issue by lxchurbakov** [tayurus/tetris-tanks-online#2]
# Description

Этот репозиторий страдает от недостатка Issues. Необходимо создать несколько and assign to me please. @tayurus

**Comment by lxchurbakov** [comment]
И не забудьте пригласить меня в разделе manage access в настройках репозитория

**Comment by lxchurbakov** [comment]
[Вот тут](https://github.com/tayurus/tetris-tanks-online/settings/access)

**Comment by tayurus** [comment]
@mcfinley сделал контрибутором. Такси на подходе!

**Comment by lxchurbakov** [comment]
Такси хаха
